### ISSUE TITLE
Game crashes when using F3+Esc to pause

### ISSUE THREAD

**Issue by dher383** [MORIMORI0317/GameMenuRemoveGFARB#3]
My game crashes when using F3+Esc to pause,here the crash report.
[crash-2022-08-10_00.42.29-client.txt](https://github.com/MORIMORI0317/GameMenuRemoveGFARB/files/9293011/crash-2022-08-10_00.42.29-client.txt)

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/game-menu-remove-gfarb/files/3928449
Released a version that seems to have fixed it.

**Comment by dher383** [comment]
It fixed,thanks a lot.
